spring:
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem:test
            driver-class-name: org.h2.Driver
            username:
            password:
    jpa:
        database: h2
        generate-ddl: true
        hibernate:
            ddl-auto: create