spring:
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem:test
            driver-class-name: org.h2.Driver
            username:
            password:
    jpa:
        database: h2
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
apis:
    scrap-api : https://codetest.3o3.co.kr/v1/scrap